### ISSUE TITLE
Links to non-existent pages should be different color

### ISSUE THREAD

**Issue by prusnak** [satoshilabs/wiki.trezor.io#1]
I would expect to see links to non-existent pages with different color. Wikipedia uses red for non-existent, blue for existent.

On our Welcome page https://wiki.trezor.io/Welcome all 3 links are blue, which is confusing.

**Comment by MrMebelMan** [comment]
Updated **MediaWiki:Vector.css** to fix it.

**Comment by sipak** [comment]
This was an intentional experiment trying to make readers experience more fluent by making all links in one non-distracting color. Links to non-existent pages where still in red when hovered over.

As for the Welcome page, this is currently being worked on.
